agents/urls.py
from django.urls import path
from . import views


app_name = 'agents'


urlpatterns = [
    
    path('', views.AgentListView.as_view(), name='agent-list'),
    path('create/', views.AgentCreateView.as_view(), name='agent-create'),
    path('agent-detail/<int:pk>', views.AgentDetailView.as_view(), name='agent-detail'),
    path('agent-update/<int:pk>', views.AgentUpdateView.as_view(), name='agent-update'),
    path('agent-confirm-delete/<int:pk>', views.AgentConfirmDeleteView.as_view(), name='agent-confirm-delete')
]

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    # path('',views.index, name='home' ),
    path('',views.HomePageView.as_view(), name='home' ),
    # path('lead-list/', views.lead_list, name='lead-list'),
    path('lead-list/', views.LeadListView.as_view(), name='lead-list'),
    # path('lead-list/<int:pk>', views.lead_detail_list, name='lead-detail'),
    path('lead-list/<int:pk>', views.LeadDetailView.as_view(), name='lead-detail'),
    # path('lead-create/', views.lead_create, name='lead-create'),
    path('lead-create/', views.LeadCreateView.as_view(), name='lead-create'),
    path('created-successfully/', views.SuccessCreateView.as_view()),
    # path('lead-update/<int:pk>', views.lead_update, name='lead-update'),
    path('lead-update/<int:pk>', views.LeadUpdateView.as_view(), name='lead-update'),
    path('lead-confirm-update/', views.lead_update_alert, name='lead-update-alert'),
    # path('lead-confirm-delete/<int:pk>', views.lead_delete, name='lead-confirm-delete'),
    path('lead-confirm-delete/<int:pk>', views.LeadDeleteView.as_view(), name='lead-confirm-delete'),
    path('lead-delete-alert/', views.delete_alert, name='delete-alert'),
    
    path('assign-agent/<int:pk>', views.AssignAgentView.as_view(), name='assign-agent'),
    path('agent-assigned-update/', views.agent_assigned_alert, name='agent-assigned-update'),
    
    
    path('categories/', views.CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    
    path('category/<int:pk>',views.LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('category-confirm-update/', views.category_confirm_update, name='category-confirm-update'),

    
    
    
    
    
]

stanCRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
    
)
from leads import views


# app_name = 'leads'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls', namespace='leads')),
    path('signup/',views.SignupView.as_view(), name='signup' ),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm' ),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    
    path('agents/', include('agents.urls', namespace='agents')),
    
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
    
    is_organiser = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)
    
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
    
    
    
    

class Lead(models.Model):
    
    SOURCE_CHOICES = (
        
        ('Facebook', 'Facebook'),
        ('Instagram', 'Instagram'),
        ('Google', 'Google'),
        ('YouTube', 'YouTube'),
        ('Newsletter', 'Newsletter'),
    )
    
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    email = models.EmailField(default="lead@example.com")
    phone = models.CharField(max_length=20, default=+44)
    description = models.CharField(max_length=255, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    source = models.CharField(choices=SOURCE_CHOICES, max_length=100)
    
    # profile_picture = models.ImageField(blank=True, null=True)
    # special_files = models.FileField(blank=True, null=True)
    
    organisations = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category",null=True, blank=True, related_name="leads", on_delete=models.SET_NULL)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisations = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.user.email}"
    

class Category(models.Model):
    name = models.CharField(max_length=30) 
    organisations = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name
    


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)       

post_save.connect(post_user_created_signal, sender=User)    

leads/forms.py
from django import forms 
from .models import Lead, User, Agent, Category

from django.contrib.auth.forms import UserCreationForm



class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'
        
        
# Becasue we created our own User, we also need to create our sign up form
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",) 




class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())
    
    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisations=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents
        
        


class LeadcategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)
            

leads/views.py
from typing import Any, Dict
from django.urls import reverse
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from .models import Lead, Category
from .forms import (
    LeadForm, 
    CustomUserCreationForm, 
    AssignAgentForm,
    LeadcategoryUpdateForm
)
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganiserAndLoginRequiredMixin


# Create your views here.



# Home Page View
######################################################

#generic base view
###################
class HomePageView(generic.TemplateView):
    template_name = 'index.html'

#function base view
###################
def index(request):
    return render(request, 'index.html')

######################################################



# List View 
######################################################

#generic base view
###################
class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = 'lead_list.html'
    context_object_name = "leads"
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisations=user.userprofile, agent__isnull=False )
        else:
            queryset = Lead.objects.filter(organisations=user.agent.organisations, agent__isnull=False)
            #filter for the agent that is loggedin
            queryset = queryset.filter(agent__user=user)
            
        return queryset    
    
    # seperate assigned and unassigned leads
    
    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organiser:
            queryset = Lead.objects.filter(
                organisations=user.userprofile, 
                agent__isnull=True,
            )
            context.update(
                {
                    'unassigned_leads': queryset
                }
            )
        return context
        
        
#function base view
###################
def lead_list(request):
    
    leads = Lead.objects.all()
    context = {'leads': leads}  
    return render(request, 'lead_list.html', context)


######################################################




# List Detail View 
######################################################

#generic base view
###################
class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'lead_detail.html'
    context_object_name = "lead"
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisations=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisations=user.agent.organisations)
            #filter for the agent that is loggedin
            queryset = queryset.filter(agent__user=user)
            
        return queryset   

#function base view
###################
def lead_detail_list(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    context = {'lead': lead}
    return render(request, 'lead_detail.html', context)
######################################################



# Create View 
######################################################

#generic base view
###################
class LeadCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = 'lead_create.html'
    form_class = LeadForm
    # model = Lead
    # fields = '__all__'
    success_url = '/created-successfully/'
   
    
    # send email
    def form_valid(self, form):
        send_mail(
            subject='New lead created',
            message='visit site to view lead',
            from_email='test@test.com',
            recipient_list=['test2@test.com']
        )
        return super(LeadCreateView, self).form_valid(form)
     

#function base view
###################
def lead_create(request):
    form =  LeadForm()
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            form.save()
    
            return render(request, 'success.html')
    context = {'form': form}    
    return render(request, 'lead_create.html', context)    
######################################################



class SuccessCreateView(generic.TemplateView):
    template_name = 'success.html'
    
    

# Update View 
######################################################   

#generic base view
###################
class LeadUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'lead_update.html'
    fields = '__all__'
    context_object_name = 'lead'
    success_url = '/lead-confirm-update/'
    
    def get_queryset(self):
        user = self.request.user
        #initial queryset for the entire organisation
        return Lead.objects.filter(organisations=user.userprofile)
            
    


#function base view
################### 
def lead_update(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    form = LeadForm(instance=lead)
    if request.method == 'POST':
        form = LeadForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect('/lead-confirm-update/')
    
    context = {'form': form, 'lead': lead}
    return render(request, 'update.html', context)
######################################################



def lead_update_alert(request):
    return render(request, 'lead_update_alert.html')
    

# Delete View 
######################################################  

#generic base view
###################
class LeadDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'lead_delete.html'
    context_object_name = 'lead'
    success_url = '/lead-delete-alert/'
    
    def get_queryset(self):
        user = self.request.user
        #initial queryset for the entire organisation
        return Lead.objects.filter(organisations=user.userprofile)
            
#function base view
################### 
def lead_delete(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    if request.method == 'POST':
        lead.delete()
        return redirect('/lead-delete-alert/')
    context = {'lead': lead}
    return render(request, 'confirm_delete.html', context )
######################################################


def delete_alert(request):
    context = {'alert': 'Successfully deleted'}
    return render(request, 'delete_alert.html', context)




# Assign agent view
class AssignAgentView(OrganiserAndLoginRequiredMixin, generic.FormView):
    template_name = 'assign_agent.html'
    form_class = AssignAgentForm
    success_url = '/agent-assigned-update/'
    
    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update(
            {
            'request': self.request,
    
        }
        ) 
        return kwargs


    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

# class SignupFormView(generic.TemplateView):
#     template_name = 'registration/signup.html'

class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm
    success_url = '/login'
    
    
def agent_assigned_alert(request):
    return render(request, 'agent_assigned_alert.html')    
    
    
# Category

class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'category_list.html'
    context_object_name = "category_list"
    
    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        
        if user.is_organiser:
            queryset = Lead.objects.filter(organisations=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisations=user.agent.organisations)
           
        
        context.update({
            "unassigned_lead_count": queryset.filter(category__isnull=True).count()
        })
        return context
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Category.objects.filter(organisations=user.userprofile)
        else:
            queryset = Category.objects.filter(organisations=user.agent.organisations)
           
        return queryset   
    
    
class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'category_detail.html'    
    context_object_name = "category"
    
    # def get_context_data(self, **kwargs):
    #     context = super(CategoryDetailView, self).get_context_data(**kwargs)
        
    #     leads = self.get_object().leads.all()
        
    #     context.update({
    #         "leads": leads
    #     })
    #     return context
    
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Category.objects.filter(organisations=user.userprofile)
        else:
            queryset = Category.objects.filter(organisations=user.agent.organisations)
           
        return queryset   
    



class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'lead_category_update.html'  
    
    form_class = LeadcategoryUpdateForm
    context_object_name = 'lead'
    # success_url = '/category-confirm-update/'
    
    def get_success_url(self):

leads/templates/partials/_footer.html
{% load static %}


<footer class="text-gray-600 body-font">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">StansCRM</span>
    </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2023 StansCRM —
      <a href="https://twitter.com/warrenstan" class="text-gray-600 underline  hover:text-indigo-500 hover:underline ml-1" rel="noopener noreferrer" target="_blank">@warrenstan</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a href="#" class="text-blue-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a href="https://twitter.com/warrenstan" class="ml-3 text-blue-400" target="_blank">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a href="#" class="ml-3 text-red-400">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a href="#" class="ml-3 text-blue-500 ">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>

leads/templates/partials/_header.html
{% load static %}


<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        {% comment %} <img class="w-48" src="{% static 'img/logo.png' %}" alt=""> {% endcomment %}
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
          </svg>
        <span class="ml-3 text-xl">StansCRM</span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <a href="{% url 'leads:home' %}" class="mr-5 hover:text-indigo-500">Home</a>
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-indigo-500">Leads</a>

        <a href="{% url 'leads:category-list' %}" class="mr-5 hover:text-indigo-500">Category</a>

        {% if request.user.is_organiser %}
        <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-indigo-500">Agents</a>
        {% endif %}
        
        {% if not request.user.is_authenticated %}
        <a href="{% url 'signup' %}" class="mr-5 hover:text-indigo-500">Sign up</a>
        {% endif %}
      </nav>

      
      {% if request.user.is_authenticated %}
        
      {{request.user.username}}
      <a href=" {% url 'logout' %} " class="inline-flex ml-4 items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none text-white bg-indigo-500 hover:bg-indigo-700 rounded text-base mt-4 md:mt-0">Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      
      {% else %}
        
      <a href=" {% url 'login' %} " class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none text-white bg-indigo-500 hover:bg-indigo-700 rounded text-base mt-4 md:mt-0">Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>

      {% endif %}
    </div>
  </header>