leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    # path('',views.index, name='home' ),
    path('',views.HomePageView.as_view(), name='home' ),
    # path('lead-list/', views.lead_list, name='lead-list'),
    path('lead-list/', views.LeadListView.as_view(), name='lead-list'),
    # path('lead-list/<int:pk>', views.lead_detail_list, name='lead-detail'),
    path('lead-list/<int:pk>', views.LeadDetailView.as_view(), name='lead-detail'),
    # path('lead-create/', views.lead_create, name='lead-create'),
    path('lead-create/', views.LeadCreateView.as_view(), name='lead-create'),
    path('created-successfully/', views.SuccessCreateView.as_view()),
    # path('lead-update/<int:pk>', views.lead_update, name='lead-update'),
    path('lead-update/<int:pk>', views.LeadUpdateView.as_view(), name='lead-update'),
    path('lead-confirm-update/', views.lead_update_alert, name='lead-update-alert'),
    # path('lead-confirm-delete/<int:pk>', views.lead_delete, name='lead-confirm-delete'),
    path('lead-confirm-delete/<int:pk>', views.LeadDeleteView.as_view(), name='lead-confirm-delete'),
    path('lead-delete-alert/', views.delete_alert, name='delete-alert'),
    
    path('assign-agent/<int:pk>', views.AssignAgentView.as_view(), name='assign-agent'),
    path('agent-assigned-update/', views.agent_assigned_alert, name='agent-assigned-update'),
    
    
    path('categories/', views.CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    
    path('category/<int:pk>',views.LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('category-confirm-update/', views.category_confirm_update, name='category-confirm-update'),

    
    
    
    
    
]

stanCRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
    
)
from leads import views


# app_name = 'leads'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls', namespace='leads')),
    path('signup/',views.SignupView.as_view(), name='signup' ),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm' ),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    
    path('agents/', include('agents.urls', namespace='agents')),
    
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
    
    is_organiser = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)
    
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
    
    
    
    

class Lead(models.Model):
    
    SOURCE_CHOICES = (
        
        ('Facebook', 'Facebook'),
        ('Instagram', 'Instagram'),
        ('Google', 'Google'),
        ('YouTube', 'YouTube'),
        ('Newsletter', 'Newsletter'),
    )
    
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    email = models.EmailField(default="lead@example.com")
    phone = models.CharField(max_length=20, default=+44)
    description = models.CharField(max_length=255, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    source = models.CharField(choices=SOURCE_CHOICES, max_length=100)
    
    # profile_picture = models.ImageField(blank=True, null=True)
    # special_files = models.FileField(blank=True, null=True)
    
    organisations = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category",null=True, blank=True, related_name="leads", on_delete=models.SET_NULL)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisations = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.user.email}"
    

class Category(models.Model):
    name = models.CharField(max_length=30) 
    organisations = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name
    


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)       

post_save.connect(post_user_created_signal, sender=User)    

leads/forms.py
from django import forms 
from .models import Lead, User, Agent, Category

from django.contrib.auth.forms import UserCreationForm



class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'
        
        
# Becasue we created our own User, we also need to create our sign up form
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",) 




class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())
    
    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisations=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents
        
        


class LeadcategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)
            

leads/views.py
from typing import Any, Dict
from django.urls import reverse
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.core.mail import send_mail
from .models import Lead, Category
from .forms import (
    LeadForm, 
    CustomUserCreationForm, 
    AssignAgentForm,
    LeadcategoryUpdateForm
)
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganiserAndLoginRequiredMixin


# Create your views here.



# Home Page View
######################################################

#generic base view
###################
class HomePageView(generic.TemplateView):
    template_name = 'index.html'

#function base view
###################
def index(request):
    return render(request, 'index.html')

######################################################



# List View 
######################################################

#generic base view
###################
class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = 'lead_list.html'
    context_object_name = "leads"
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisations=user.userprofile, agent__isnull=False )
        else:
            queryset = Lead.objects.filter(organisations=user.agent.organisations, agent__isnull=False)
            #filter for the agent that is loggedin
            queryset = queryset.filter(agent__user=user)
            
        return queryset    
    
    # seperate assigned and unassigned leads
    
    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organiser:
            queryset = Lead.objects.filter(
                organisations=user.userprofile, 
                agent__isnull=True,
            )
            context.update(
                {
                    'unassigned_leads': queryset
                }
            )
        return context
        
        
#function base view
###################
def lead_list(request):
    
    leads = Lead.objects.all()
    context = {'leads': leads}  
    return render(request, 'lead_list.html', context)


######################################################




# List Detail View 
######################################################

#generic base view
###################
class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'lead_detail.html'
    context_object_name = "lead"
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Lead.objects.filter(organisations=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisations=user.agent.organisations)
            #filter for the agent that is loggedin
            queryset = queryset.filter(agent__user=user)
            
        return queryset   

#function base view
###################
def lead_detail_list(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    context = {'lead': lead}
    return render(request, 'lead_detail.html', context)
######################################################



# Create View 
######################################################

#generic base view
###################
class LeadCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = 'lead_create.html'
    form_class = LeadForm
    # model = Lead
    # fields = '__all__'
    success_url = '/created-successfully/'
   
    
    # send email
    def form_valid(self, form):
        send_mail(
            subject='New lead created',
            message='visit site to view lead',
            from_email='test@test.com',
            recipient_list=['test2@test.com']
        )
        return super(LeadCreateView, self).form_valid(form)
     

#function base view
###################
def lead_create(request):
    form =  LeadForm()
    if request.method == 'POST':
        form = LeadForm(request.POST)
        if form.is_valid():
            form.save()
    
            return render(request, 'success.html')
    context = {'form': form}    
    return render(request, 'lead_create.html', context)    
######################################################



class SuccessCreateView(generic.TemplateView):
    template_name = 'success.html'
    
    

# Update View 
######################################################   

#generic base view
###################
class LeadUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'lead_update.html'
    fields = '__all__'
    context_object_name = 'lead'
    success_url = '/lead-confirm-update/'
    
    def get_queryset(self):
        user = self.request.user
        #initial queryset for the entire organisation
        return Lead.objects.filter(organisations=user.userprofile)
            
    


#function base view
################### 
def lead_update(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    form = LeadForm(instance=lead)
    if request.method == 'POST':
        form = LeadForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect('/lead-confirm-update/')
    
    context = {'form': form, 'lead': lead}
    return render(request, 'update.html', context)
######################################################



def lead_update_alert(request):
    return render(request, 'lead_update_alert.html')
    

# Delete View 
######################################################  

#generic base view
###################
class LeadDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'lead_delete.html'
    context_object_name = 'lead'
    success_url = '/lead-delete-alert/'
    
    def get_queryset(self):
        user = self.request.user
        #initial queryset for the entire organisation
        return Lead.objects.filter(organisations=user.userprofile)
            
#function base view
################### 
def lead_delete(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    if request.method == 'POST':
        lead.delete()
        return redirect('/lead-delete-alert/')
    context = {'lead': lead}
    return render(request, 'confirm_delete.html', context )
######################################################


def delete_alert(request):
    context = {'alert': 'Successfully deleted'}
    return render(request, 'delete_alert.html', context)




# Assign agent view
class AssignAgentView(OrganiserAndLoginRequiredMixin, generic.FormView):
    template_name = 'assign_agent.html'
    form_class = AssignAgentForm
    success_url = '/agent-assigned-update/'
    
    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update(
            {
            'request': self.request,
    
        }
        ) 
        return kwargs


    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)

# class SignupFormView(generic.TemplateView):
#     template_name = 'registration/signup.html'

class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm
    success_url = '/login'
    
    
def agent_assigned_alert(request):
    return render(request, 'agent_assigned_alert.html')    
    
    
# Category

class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'category_list.html'
    context_object_name = "category_list"
    
    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        
        if user.is_organiser:
            queryset = Lead.objects.filter(organisations=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisations=user.agent.organisations)
           
        
        context.update({
            "unassigned_lead_count": queryset.filter(category__isnull=True).count()
        })
        return context
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Category.objects.filter(organisations=user.userprofile)
        else:
            queryset = Category.objects.filter(organisations=user.agent.organisations)
           
        return queryset   
    
    
class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'category_detail.html'    
    context_object_name = "category"
    
    # def get_context_data(self, **kwargs):
    #     context = super(CategoryDetailView, self).get_context_data(**kwargs)
        
    #     leads = self.get_object().leads.all()
        
    #     context.update({
    #         "leads": leads
    #     })
    #     return context
    
    
    def get_queryset(self):
        user = self.request.user
        
        #initial queryset for the entire organisation
        if user.is_organiser:
            queryset = Category.objects.filter(organisations=user.userprofile)
        else:
            queryset = Category.objects.filter(organisations=user.agent.organisations)
           
        return queryset   
    



class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'lead_category_update.html'  
    
    form_class = LeadcategoryUpdateForm
    context_object_name = 'lead'
    # success_url = '/category-confirm-update/'
    
    def get_success_url(self):

leads/templates/category_list.html
{% extends 'base.html' %}


{% load static %}



{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Category</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Segments the leads by their categories</p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead count</th>
              <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
            </tr>
          </thead>
          <tbody>

            <tr>
                <td class="px-4 py-3"> <a class="text-indigo-500 underline hover:text-indigo-700" href="{% url 'leads:lead-list' %}">Unassigned</a> </td>
                <td class="px-4 py-3"> {{unassigned_lead_count}} </td>
              
              </tr>


           
           {% for category in category_list %}

           <tr>
            <td class="px-4 py-3 "> <a class="text-indigo-500 underline hover:text-indigo-500" href="{% url 'leads:category-detail' category.pk %}">{{category.name}}</a> </td>
            <td class="px-4 py-3"> ToDO count </td>
          
          </tr>
         
            
           {% endfor %}
            
          </tbody>
        </table>
      </div>
      
    </div>
  </section>



    
{% endblock content %}
    

leads/templates/lead_category_update.html
{% extends 'base.html' %}

{% load static %}

{% load tailwind_filters %}

{% block content %}


<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex justify-center flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} {{lead.last_name}}</h1>
          <div class="flex mb-4">
            <a  href=" {% url 'leads:lead-detail' lead.pk  %} "  class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"  >Overview</a>
            <a href="{% url 'leads:lead-category-update' lead.pk %}"  class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
            <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"   >Update</a>
          </div>
          <form action="" method="POST">

            {% csrf_token %}
    
            {{form|crispy}}
    
            
            <button class="w-full bg-indigo-500 text-white hover:bg-indigo-700 px-3 py-2 my-2 rounded-md " type="submit">Update category</button>

        </form>

        <div class="flex justify-center">
            
            
          <a href="{% url 'leads:lead-confirm-delete' lead.pk %}" class="w-full bg-red-600 text-white text-center hover:bg-red-700 px-3 py-2 my-2 rounded-md">Delete</a>
         
        </div>
          <div class="flex my-3">
            <a href="{% url 'leads:lead-list' %}" class="w-full text-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Back to leads</a>
            
            {% comment %} <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button> {% endcomment %}
          </div>
        </div>
        {% comment %} <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400"> {% endcomment %}
      </div>
    </div>
  </section>



{% endblock  %}

leads/templates/lead_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Leads</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category-list' %}">
                    View categories
                </a>
            </div>
      
            {% if request.user.is_organiser %}
            <div>
                <a class="text-indigo-500 hover:text-blue-500" href="{% url 'leads:lead-create' %}">
                    Create a new lead
                </a>
            </div>
            {% endif %}
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            First Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Last Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Age
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Cell Phone Number
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Agent
                              </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Category
                            </th>
                            
                            
                              
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                           
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a class="text-blue-500 hover:text-blue-800" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.last_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.age }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.email }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.phone_number }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                  {{ lead.agent }}
                              </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {% if lead.category %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ lead.category.name }}
                                        </span>
                                    {% else %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Unassigned
                                        </span>
                                    {% endif %}
                                </td>
                                {%  if request.user.is_organiser  %}
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'leads:lead-update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Edit
                                    </a>
                                </td>

                                {% elif request.user.is_agent %}

                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                  <a href="{% url 'leads:lead-detail' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                      View
                                  </a>
                              </td>


                                {% endif %}
                            </tr>

                        {% empty %}

                        <p class="text-red-500">There are currently no leads</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
  
        {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ lead.first_name }} {{ lead.last_name }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{ lead.description }}
                            </p>
                            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign an agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

leads/templates/lead_update.html
{% extends 'base.html' %}

{% load static %}

{% load tailwind_filters %}

{% block content %}


<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex justify-center flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} {{lead.last_name}}</h1>
          <div class="flex mb-4">
            <a  href=" {% url 'leads:lead-detail' lead.pk  %} " class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"  >Overview</a>
            <a href="{% url 'leads:lead-category-update' lead.pk %}"  class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
            <a href="{% url 'leads:lead-update' lead.pk %}"  class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
          </div>
          <form action="" method="POST" >

            {% csrf_token %}
    
            {{form|crispy}}
    
            {% comment %} <input class="w-full bg-indigo-500 text-white hover:bg-indigo-700 px-3 py-2 my-2 rounded-md " type="submit"> {% endcomment %}
            <button class="w-full bg-indigo-500 text-white hover:bg-indigo-700 px-3 py-2 my-2 rounded-md " type="submit">Update</button>

         </form>
          <div class="flex justify-center">
            
            
            <a href="{% url 'leads:lead-confirm-delete' lead.pk %}" class="w-full bg-red-600 text-white text-center hover:bg-red-700 px-3 py-2 my-2 rounded-md">Delete</a>
           
          </div>
          <div class="my-3">
            <a href="{% url 'leads:lead-list' %}" class="w-full text-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Back to leads</a>
            <!-- <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button> -->
          </div>
        </div>
        {% comment %} <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400"> {% endcomment %}
      </div>
    </div>
  </section>



{% endblock  %}