agents/urls.py
from django.urls import path
from . import views


app_name = 'agents'


urlpatterns = [
    
    path('', views.AgentListView.as_view(), name='agent-list'),
    path('create/', views.AgentCreateView.as_view(), name='agent-create'),
    path('agent-detail/<int:pk>', views.AgentDetailView.as_view(), name='agent-detail'),
    path('agent-update/<int:pk>', views.AgentUpdateView.as_view(), name='agent-update'),
    path('agent-confirm-delete/<int:pk>', views.AgentConfirmDeleteView.as_view(), name='agent-confirm-delete')
]

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    # path('',views.index, name='home' ),
    path('',views.HomePageView.as_view(), name='home' ),
    # path('lead-list/', views.lead_list, name='lead-list'),
    path('lead-list/', views.LeadListView.as_view(), name='lead-list'),
    # path('lead-list/<int:pk>', views.lead_detail_list, name='lead-detail'),
    path('lead-list/<int:pk>', views.LeadDetailView.as_view(), name='lead-detail'),
    # path('lead-create/', views.lead_create, name='lead-create'),
    path('lead-create/', views.LeadCreateView.as_view(), name='lead-create'),
    path('created-successfully/', views.SuccessCreateView.as_view()),
    # path('lead-update/<int:pk>', views.lead_update, name='lead-update'),
    path('lead-update/<int:pk>', views.LeadUpdateView.as_view(), name='lead-update'),
    path('lead-confirm-update/', views.lead_update_alert, name='lead-update-alert'),
    # path('lead-confirm-delete/<int:pk>', views.lead_delete, name='lead-confirm-delete'),
    path('lead-confirm-delete/<int:pk>', views.LeadDeleteView.as_view(), name='lead-confirm-delete'),
    path('lead-delete-alert/', views.delete_alert, name='delete-alert'),
    
    path('assign-agent/<int:pk>', views.AssignAgentView.as_view(), name='assign-agent'),
    path('agent-assigned-update/', views.agent_assigned_alert, name='agent-assigned-update'),
    
    
    path('categories/', views.CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    
    path('category/<int:pk>',views.LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('category-confirm-update/', views.category_confirm_update, name='category-confirm-update'),

    
    
    
    
    
]

stanCRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
    
)
from leads import views


# app_name = 'leads'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls', namespace='leads')),
    path('signup/',views.SignupView.as_view(), name='signup' ),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(), name='password_reset_confirm' ),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    
    path('agents/', include('agents.urls', namespace='agents')),
    
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms 
from leads.models import Agent
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


# class AgentModelForm(forms.ModelForm):
#     class Meta:
#         model = Agent
#         fields = ('user',)


User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )
                

agents/views.py
import random

from typing import Any
from django.db.models.query import QuerySet
from .forms import AgentModelForm
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .mixins import OrganiserAndLoginRequiredMixin
from django.core.mail import send_mail


# Create your views here.

class AgentListView(OrganiserAndLoginRequiredMixin, generic.ListView):
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisations=organisation)
    

class AgentCreateView(OrganiserAndLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent_create.html'  
    form_class = AgentModelForm
    
    success_url = '/agents/'
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organiser = False
        user.save()
        user.set_password(f"{random.randint(0, 1000000)}")
        Agent.objects.create(
            user=user,
            organisations=self.request.user.userprofile
        )
        send_mail(
            subject='You are invited to be an agent',
            message='You were added as an agent in StansCRM. Please click the link to login',
            from_email='admin@stanscrm.com',
            recipient_list=[user.email]
        )
        return super(AgentCreateView, self).form_valid(form)
    
    
    # def form_valid(self, form):
    #     agent = form.save(commit=False)
    #     agent.organisations = self.request.user.userprofile
    #     agent.save()
    #     return super(AgentCreateView, self).form_valid(form)
    
    
class AgentDetailView(OrganiserAndLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/agent_detail.html'   
    context_object_name = 'agent'
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisations=organisation)



class AgentUpdateView(OrganiserAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'agents/agent_update.html' 
    model = Agent
    fields = '__all__'  
    success_url = '/agents/'
    
    
    
class AgentConfirmDeleteView(OrganiserAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent_confirm_delete.html'  
    context_object_name = 'agent' 
    success_url = '/agents/'
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisations=organisation)

agents/templates/agents/agent_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=h, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Confirm Delete</h1>

    <form action="" method="POST">

        {% csrf_token %}
        <h3>Are you sure you want to delete {{agent}} ? </h3>
        <p>This action cannot be undone</p>

        <div style="display: flex; gap:20px;">
            <input style="background: red; color:white; padding:8px" type="submit" value="Yes! delete data">

        <a href="{% url 'agents:agent-detail' agent.pk %}"> No! I change my mind</a>
        </div>
        
    </form>

    
</body>
</html>

agents/templates/agents/agent_create.html
{% extends 'base.html' %}

{% load static %}

{% load tailwind_filters %}

{% block content %}



<div class="w-2/5 m-auto px-8">

  <h1 class="text-2xl my-4"> Create a new agent</h1>

  <div class="max-w-lg mx-auto my-6 border px-12 py-12 ">

    <form action="" method="POST">
  
      {% csrf_token %}
  
      {{form|crispy}}
  
      <button class="w-full bg-indigo-500 text-white hover:bg-indigo-700 px-3 py-2 my-2 rounded-md " type="submit">Create agent</button>
  
    </form>
  
  </div>
  

</div>
    
{% endblock  %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %}
{% load  static %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{agent.user.first_name}} {{agent.user.last_name}}</h1>
          <div class="flex mb-4">
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
          </div>
          <p class="leading-relaxed mb-4"> {{lead.description}} </p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Username: </span>
            <span class="ml-auto text-gray-900">{{agent.user.username}}</span>
          </div>
          
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Email: </span>
            <span class="ml-auto text-gray-900">{{agent.user.email}}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Source</span>
            <span class="ml-auto text-gray-900">{{agent.user.source}} </span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">{{agent.user.location}}</span>
          </div>
          <div class="flex">

            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Update</a>
            <a href="{% url 'agents:agent-list' %}" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Back to agents</a>
            

            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>



{% endblock  %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Agents</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-indigo-500" href="{% url 'agents:agent-create' %}">Create a new agent</a>
                </div>
            </div>

            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Full Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Email
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for agent in object_list %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ agent.user.first_name }} {{ agent.user.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ agent.user.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'agents:agent-update' agent.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}

                            <p class="text-red-500">There are currently no agents</p>

                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>

        </div>
      </section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %}

{% load static %}

{% load tailwind_filters %}

{% block content %}


<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex justify-center flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4"> {{lead.first_name}} {{lead.last_name}}</h1>
          <div class="flex mb-4">
            <a  href=" {% url 'agents:agent-detail' agent.pk  %} " class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"  >Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'agents:agent-update' agent.pk %}"  class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
          </div>
          <form action="" method="POST">

            {% csrf_token %}
    
            {{form|crispy}}
    
            
            <button class="w-full bg-indigo-500 text-white hover:bg-indigo-700 px-3 py-2 my-2 rounded-md " type="submit">Update agent</button>
        </form>

        <div class="flex justify-center">
            
            
          <a href="{% url 'agents:agent-confirm-delete' agent.pk %}" class="w-full bg-red-600 text-white text-center hover:bg-red-700 px-3 py-2 my-2 rounded-md">Delete</a>
         
        </div>

        <div class="flex  w-3/6 mx-auto  my-3">
          <a href="{% url 'agents:agent-list' %}" class="w-full text-center text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Back to agents</a>
          <!-- <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button> -->
        </div>
        </div>
        {% comment %} <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400"> {% endcomment %}
      </div>
    </div>
</section>







{% endblock  %}